airbnb:
  outputs:
    dev:
      type: snowflake
      account: vosqysc-dkb10382
      user: dbt

      role: TRANSFORM
      private_key_path: "c:\\Users\\kenis\\Projects\\dbt-course\\airbnb\\snowflake_rsa_key.p8"
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
